name: epanet2-win32

on: 
  push:
  pull_request: 
  schedule: 
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Setup build directory
        run: mkdir buildproducts
        
      - name: CMake
        working-directory: ./buildproducts
        run: cmake .. -A Win32 && cmake --build . --config Release

      - name: Copy header files to build directory
        run: |
          copy include\epanet2.h buildproducts\bin\Release
          copy include\epanet2_2.h buildproducts\bin\Release
          copy include\epanet2_enums.h buildproducts\bin\Release
        shell: cmd
        
      - uses: actions/upload-artifact@v2
        with:
          name: epanet2-win32
          path: buildproducts\bin\Release